nginx:
    image: tutum/nginx
    ports: 
        - "80:80"
    links: 
        - phpfpm
    volumes: 
        - ./nginx/default:/etc/nginx/sites-available/default
        - ./nginx/default:/etc/nginx/sites-enabled/default

        - ./logs/nginx-error.log:/var/logs/nginx/error.log
        - ./logs/nginx-access.log:/var/logs/nginx/access.log
phpfpm: 
    image: php:fpm
    ports: 
        - "9000:9000"
    volumes: 
        - ./html:/usr/share/nginx/html
mysql: 
  image: mariadb
  environment: 
    MYSQL_ROOT_PASSWORD: admin
  volumes: 
        - ./mysql:/var/lib/mysql
    
